version: '3'

services:
  web:
    build: .
    command: bash -c "
      sleep 10
      && python manage.py makemigrations scrapper
      && python manage.py makemigrations
      && python manage.py migrate
      && pytest scrapper/tests.py
      && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres

  my-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mypassword